INSERT INTO EMPLOYEE_SCHEMA(ID, NAME) VALUES (1, 'Elsa');
INSERT INTO EMPLOYEE_SCHEMA(ID, NAME) VALUES (2, 'Anna');
INSERT INTO EMPLOYEE_SCHEMA(ID, NAME) VALUES (3, 'Elsia');
INSERT INTO EMPLOYEE_SCHEMA(ID, NAME) VALUES (4, 'Annia');
INSERT INTO EMPLOYEE_SCHEMA(ID, NAME) VALUES (5, 'Chelse');
INSERT INTO EMPLOYEE_SCHEMA(ID, NAME) VALUES (6, 'Isabel');
INSERT INTO EMPLOYEE_SCHEMA(ID, NAME) VALUES (7, 'Anabel');
INSERT INTO EMPLOYEE_SCHEMA(ID, NAME) VALUES (8, 'Tricksy');